apiVersion: apps/v1
kind: Deployment
metadata:
  name: nymeria-gcloud
  namespace: workload-identity
  labels:
    app: nymeria
    cloud: gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nymeria
      cloud: gcp
  template:
    metadata:
      name: nymeria-gcloud
      labels:
        app: nymeria
        cloud: gcp
    spec:
      serviceAccountName: nymeria
      volumes:
        - name: gcp-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3600
                  audience: ${gcp_oidc_audience}
              - configMap:
                  name: gcloud-client-configuration
                  items:
                    - key: client.json
                      path: client-config.json
      containers:
        - name: gcloud
          image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: 1Gi
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: 1Gi
          volumeMounts:
            - mountPath: ${identity_token_mount_path}
              name: gcp-token
          env:
            - name: NYMERIA_STORAGE_BUCKET
              value: ${nymeria_storage_bucket}
      nodeSelector:
        kubernetes.io/os: linux
