apiVersion: v1
kind: Secret
metadata:
  name: azure-service-principal
  namespace: static-credential
  labels:
    app: nymeria
    cloud: azure
data:
  tenant_id: ${azure_tenant_id}
  client_id: ${azure_client_id}
  client_secret: ${azure_client_secret}
