apiVersion: v1
kind: Secret
metadata:
  name: azure-service-principal
  namespace: static-credential
  labels:
    app: nymeria
    cloud: azure
data:
  ARM_TENANT_ID: ${azure_tenant_id}
  ARM_CLIENT_ID: ${azure_client_id}
  ARM_CLIENT_SECRET: ${azure_client_secret}
