apiVersion: apps/v1
kind: Deployment
metadata:
  name: nymeria-gcloud
  namespace: static-credential
  labels:
    app: nymeria
    cloud: gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nymeria
      cloud: gcp
  template:
    metadata:
      name: nymeria-gcloud
      labels:
        app: nymeria
        cloud: gcp
    spec:
      containers:
        - name: gcloud
          image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: 1Gi
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: 1Gi
          volumeMounts:
            - name: gcp-service-account-key
              mountPath: /mnt/service-account/
          env:
            - name: NYMERIA_STORAGE_BUCKET
              value: ${nymeria_storage_bucket}
      volumes:
        - name: gcp-service-account-key
          secret:
            secretName: gcp-service-account-key
      nodeSelector:
        kubernetes.io/os: linux
