---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    nymeria/owner: "nymeria"
    nymeria/cost-center: "rsa"
  name: "nymeria"
  namespace: workload-identity
  labels:
    app: nymeria
    cloud: gcp
